# Generated by Django 4.2.2 on 2023-06-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=500, verbose_name='Todo list point name')),
                ('checked', models.BooleanField(default=False, verbose_name='Complited')),
                ('code', models.TextField()),
            ],
        ),
    ]
